apiVersion: v1
kind: Service
metadata:
  labels:
    app: swl-oldtoronto-web
  name: swl-oldtoronto-web
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: swl-oldtoronto-web
  type: NodePort
